name: Create Schema Document

on:
  push:
    

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 -v ${{ github.workspace }}/init.sql:/docker-entrypoint-initdb.d/init.sql

    steps:
      - name: Checkout
        uses: actions/checkout@v3