name: Create Schema Document

on:
  push:
    

jobs:
  create-schema-document:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test_db
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: feat/add_github_actions

      - name: Init Schema
        run: mysql -u root -h 127.0.0.1 test_db < ./init.sql

      - name: Setup tbls
        uses: k1low/setup-tbls@v1

      - name: Run tbls
        env:
          SCHEMA: test_db
          DATABASE: test_db
        run: tbls doc

      - name: Create and switch to new branch
        run: |
          git fetch
          git switch -c update-generated-docs

      - name: Commit and push generated files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git status
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update generated documentation" || echo "No changes to commit"
          git push -u origin update-generated-docs || echo "No changes to push"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update generated documentation"
          body: "This PR updates the generated documentation."
          commit-message: "Update generated documentation"
          base: feat/add_github_actions
          branch: "update-generated-docs"
          delete-branch: true
          