name: Create Schema Document

on:
  push:
    branch:
      - 'develop'
      - 'feat/add_github_cli'
    # paths:
        # - "init.sql"


jobs:
  create-schema-document:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test_db
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout base branch
        uses: actions/checkout@v3

      - name: Init Schema
        run: mysql -u root -h 127.0.0.1 test_db < ./init.sql

      - name: Setup tbls
        uses: k1low/setup-tbls@v1

      - name: Run tbls
        env:
          SCHEMA: test_db
          DATABASE: test_db
        run: tbls doc --force

      - name: GitHub CLI
        run: gh pr list --search "sha:${{ github.sha }}" --json "url" -q ".[0].url"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: GitHub CLI
        id: store-pr-url
        run: |
          pr_url=$(gh pr list --search "sha:${{ github.sha }}" --json "url" -q ".[0].url")
          echo "url=pr_url" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Update generated documentation"
          body: "This PR updates the generated documentation by ${{ steps.store-pr-url.outputs.url }}"
          commit-message: "update generated documentation"
          base: feat/add_github_cli
          branch: feat/update-generated-docs
          reviewers: ${{ github.actor }}
          author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
          delete-branch: true
