name: Update Schema Document

on:
  push:
    branches-ignore:
      - 'master'
      - 'main'
      - 'staging'
      - 'develop'
    paths:
        - "schema.sql"

jobs:
  update-schema-document:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test_db
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout base branch
        uses: actions/checkout@v3

      - name: Init Schema
        run: mysql -u root -h 127.0.0.1 test_db < ./schema.sql

      - name: Setup tbls
        uses: k1low/setup-tbls@v1

      - name: Run tbls
        env:
          DATABASE: test_db
        run: tbls doc --force
      
      - name: Commit and Push
        run: |
          git add --update
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "update schema document"
          git push

      # - name: Load PR Infomation
      #   id: load_pr
      #   run: |
      #     pr_url=$(gh pr list --state merged --search "sha:${{ github.sha }}" --json "url" -q ".[0].url")
      #     pr_title=$(gh pr list --state merged --search "sha:${{ github.sha }}" --json "title" -q ".[0].title")
      #     pr_author=$(gh pr list --state merged --search "sha:${{ github.sha }}" --json "author" -q ".[0].author.login")
      #     echo "pr_url=${pr_url}" >> $GITHUB_OUTPUT
      #     echo "pr_title=${pr_title}" >> $GITHUB_OUTPUT
      #     echo "pr_author=${pr_author}" >> $GITHUB_OUTPUT
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Create Pull Request
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     title: "Update generated documentation"
      #     body: |
      #       [${{ steps.load_pr.outputs.pr_title }}](${{ steps.load_pr.outputs.pr_url }}) でスキーマが更新されたのでスキーマのドキュメントも更新します
      #     commit-message: "update generated documentation"
      #     base: develop
      #     branch: feat/update-generated-docs
      #     reviewers: ${{ steps.load_pr.outputs.pr_author }}
      #     author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
      #     delete-branch: true
